export {
  recipientBundleSchema,
  loadRecipientBundle,
  isPqHybridBundle,
  diffBundles,
  recipientBundlePath,
  RECIPIENTS_FOLDER,
  type RecipientBundle,
  type RecipientEntry,
  type LoadBundleResult,
  type BundleDelta,
} from "./recipient-bundle.js";
export {
  ENCRYPTED_SUFFIXES,
  hasEncryptedSuffix,
  isEnvelopeCompanion,
  matchesSensitiveGlob,
  validateSensitivePaths,
  isSensitivePath,
  logicalPath,
  encryptedPath,
  type EncryptedSuffix,
  type SensitiveGlobViolation,
} from "./sensitive-glob.js";
export {
  encrypt,
  decrypt,
  generatePqIdentity,
  generateClassicalIdentity,
  isEncryptionPipelineReady,
  envelopePath,
  writeEnvelope,
  type SensitivityTier,
  type AgeIdentityHandle,
  type AuditContext,
  type DecryptRequest,
  type DecryptResult,
  type EncryptRequest,
  type EncryptResult,
  type EnvelopeCompanion,
} from "./encryption-api.js";
export {
  isAgeAvailable,
  isAgeKeygenAvailable,
  ageEncryptToFile,
  ageDecryptFile,
  ageKeygen,
} from "./age-cli.js";
export {
  AuditLogWriter,
  AUDIT_LOG_PATH,
  auditLogPath,
  type AuditEvent,
  type AuditEventKind,
  type AuditEventBase,
  type EncryptDecryptEvent,
  type CapabilityEvent,
  type RatchetEvent,
  type DriftEvent,
  type ChangeSetEvent,
  type KeyRotationEvent,
} from "./audit-log.js";
export {
  RATCHETS_FOLDER,
  ratchetSentinelPath,
  loadRatchetSentinel,
  writeRatchetSentinel,
  startRatchet,
  completeRatchet,
  abandonRatchet,
  stealRatchet,
  findActiveRatchet,
  isValidTransition,
  verifyRecipientSetCoherence,
  VALID_TRANSITIONS,
  type RatchetState,
  type RatchetSentinel,
  type LoadSentinelResult,
  type StartRatchetOptions,
  type StealRatchetResult,
  type CoherenceCheckResult,
} from "./ratchet.js";
