/**
 * Pydantic model generator — STUB.
 *
 * The full generator emits Python `pydantic.BaseModel` subclasses for
 * every schema in `PLATFORM_ENDPOINTS`, so MSP, GTM, and any other
 * Python product server consumes a generated `platform_contract.py`
 * module instead of hand-coding its own Pydantic models that drift.
 *
 * Why stubbed:
 *   Cross-language code generation is real work — z.string().url() →
 *   pydantic.AnyUrl, z.enum → typing.Literal, z.union → typing.Union,
 *   Optional vs default handling, recursive models. Each branch needs
 *   its own golden test. Stage-2 ships TS+JSON-Schema first; pydantic
 *   follows in Stage-2b once MSP/GTM have a consumption story.
 *
 * The stub returns a single placeholder file with a header comment so
 * the architecture is set up: the compiler already knows how to
 * dispatch to this generator, and the snapshot test will diff against
 * the placeholder until a real emit lands.
 */

import type { EndpointDef } from "../schemas.js";

export interface PydanticFile {
  path: string;
  content: string;
}

export function generatePydantic(endpoints: EndpointDef[]): PydanticFile[] {
  const lines: string[] = [];
  lines.push('"""');
  lines.push("Brainstorm Platform Contract v1 — pydantic models.");
  lines.push("");
  lines.push("STUB. Real emission is tracked under Stage-2b.");
  lines.push("");
  lines.push(
    "Endpoints currently in the contract (count generated by the compiler):",
  );
  for (const ep of endpoints) {
    lines.push(`  - ${ep.method} ${ep.path}  (${ep.id})`);
  }
  lines.push('"""');
  lines.push("");
  lines.push("from __future__ import annotations");
  lines.push("");
  lines.push("# TODO(stage-2b): emit BaseModel subclasses here.");
  lines.push("");

  return [
    {
      path: "platform_contract.py",
      content: lines.join("\n") + "\n",
    },
  ];
}
