/**
 * Server dev-mode bearer token regression tests.
 *
 * v17 Auditor flagged: server dev-token has code fix (closes Attacker
 * confused-deputy) but no regression test. Closes that gap.
 *
 * The token mechanism:
 * - Generated by initDevToken() when jwtSecret is unset + bind is loopback
 * - 64 hex chars (32 bytes), written 0600 to ~/.brainstorm/server-token
 * - verifyDevToken() checks Authorization: Bearer <token> in constant time
 * - Unlinked on stop()
 *
 * Verified properties:
 *   1. initDevToken writes a 64-hex-char token with mode 0600
 *   2. verifyDevToken accepts the matching Bearer
 *   3. verifyDevToken rejects: wrong token, no header, malformed header,
 *      case-insensitive Bearer prefix
 *   4. stop() deletes the file + clears the in-memory state
 *   5. BRAINSTORM_HOME respected for the token directory
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  existsSync,
  readFileSync,
  statSync,
  mkdtempSync,
  rmSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { BrainstormServer } from "../server";

// Minimal mock deps the server needs at construction time
function makeDeps() {
  return {
    db: {} as any,
    config: {},
    registry: {} as any,
    router: {} as any,
    costTracker: {} as any,
    tools: {} as any,
    godmode: {} as any,
    memoryManager: {} as any,
    version: "test",
  } as any;
}

describe("server dev-token (v17 Attacker regression)", () => {
  let tmp: string;
  let originalHome: string | undefined;

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), "brainstorm-devtoken-"));
    originalHome = process.env.BRAINSTORM_HOME;
    process.env.BRAINSTORM_HOME = tmp;
  });

  afterEach(() => {
    if (originalHome === undefined) delete process.env.BRAINSTORM_HOME;
    else process.env.BRAINSTORM_HOME = originalHome;
    rmSync(tmp, { recursive: true, force: true });
  });

  it("initDevToken writes 64-hex token file with mode 0600", () => {
    const server = new BrainstormServer(makeDeps(), { jwtSecret: "" });
    // Private method access via cast — this is a regression test of
    // exactly that method, so we need its surface.
    (server as any).initDevToken();
    const tokenPath = (server as any).devTokenPath as string;
    const token = (server as any).devToken as string;

    expect(tokenPath).toMatch(/server-token$/);
    expect(existsSync(tokenPath)).toBe(true);
    expect(token).toMatch(/^[0-9a-f]{64}$/);
    expect(readFileSync(tokenPath, "utf-8")).toBe(token);

    const mode = statSync(tokenPath).mode & 0o777;
    expect(mode, `token file should be 0600, got 0${mode.toString(8)}`).toBe(
      0o600,
    );
  });

  it("BRAINSTORM_HOME is honored for the token directory", () => {
    const server = new BrainstormServer(makeDeps(), { jwtSecret: "" });
    (server as any).initDevToken();
    const path = (server as any).devTokenPath as string;
    expect(path.startsWith(tmp)).toBe(true);
  });

  it("verifyDevToken accepts a matching Bearer", () => {
    const server = new BrainstormServer(makeDeps(), { jwtSecret: "" });
    (server as any).initDevToken();
    const token = (server as any).devToken as string;

    const verify = (server as any).verifyDevToken.bind(server);
    expect(verify(`Bearer ${token}`)).toBe(true);
    expect(verify(`bearer ${token}`)).toBe(true); // case-insensitive
    expect(verify(`Bearer    ${token}`)).toBe(true); // multiple spaces
    expect(verify(`Bearer\t${token}`)).toBe(true); // tab whitespace
  });

  it("verifyDevToken rejects wrong token", () => {
    const server = new BrainstormServer(makeDeps(), { jwtSecret: "" });
    (server as any).initDevToken();
    const verify = (server as any).verifyDevToken.bind(server);
    // Same length as a real token (64 hex), but different bytes
    const wrong = "0".repeat(64);
    expect(verify(`Bearer ${wrong}`)).toBe(false);
  });

  it("verifyDevToken rejects empty / missing / malformed Authorization", () => {
    const server = new BrainstormServer(makeDeps(), { jwtSecret: "" });
    (server as any).initDevToken();
    const verify = (server as any).verifyDevToken.bind(server);

    expect(verify(undefined)).toBe(false);
    expect(verify("")).toBe(false);
    expect(verify("Bearer")).toBe(false); // no token
    expect(verify("Bearer ")).toBe(false); // empty token
    expect(verify("Basic dXNlcjpwYXNz")).toBe(false); // wrong scheme
    expect(verify("Token abc")).toBe(false); // wrong scheme
  });

  it("verifyDevToken rejects truncated-token (length mismatch)", () => {
    const server = new BrainstormServer(makeDeps(), { jwtSecret: "" });
    (server as any).initDevToken();
    const token = (server as any).devToken as string;
    const verify = (server as any).verifyDevToken.bind(server);
    // Length mismatch must return false BEFORE timingSafeEqual (which
    // throws on length mismatch in Node).
    expect(verify(`Bearer ${token.slice(0, -1)}`)).toBe(false);
    expect(verify(`Bearer ${token + "0"}`)).toBe(false);
  });

  it("verifyDevToken returns false when devToken has not been initialised", () => {
    const server = new BrainstormServer(makeDeps(), { jwtSecret: "" });
    const verify = (server as any).verifyDevToken.bind(server);
    // No initDevToken() call → devToken is null
    expect(
      verify(
        "Bearer 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcd",
      ),
    ).toBe(false);
  });

  it("stop() deletes the token file and clears in-memory state", async () => {
    const server = new BrainstormServer(makeDeps(), { jwtSecret: "" });
    (server as any).initDevToken();
    const tokenPath = (server as any).devTokenPath as string;
    expect(existsSync(tokenPath)).toBe(true);

    await server.stop();

    expect(existsSync(tokenPath)).toBe(false);
    expect((server as any).devToken).toBeNull();
    expect((server as any).devTokenPath).toBeNull();
  });

  it("constructing a new server overwrites the token (per-session)", () => {
    const a = new BrainstormServer(makeDeps(), { jwtSecret: "" });
    (a as any).initDevToken();
    const tokenA = (a as any).devToken as string;

    const b = new BrainstormServer(makeDeps(), { jwtSecret: "" });
    (b as any).initDevToken();
    const tokenB = (b as any).devToken as string;

    expect(tokenA).not.toBe(tokenB);
    // The file on disk reflects the LATER call
    const path = (b as any).devTokenPath as string;
    expect(readFileSync(path, "utf-8")).toBe(tokenB);
  });
});
