/**
 * API Reference Document Generator.
 *
 * Produces an API reference from the endpoint map in ProjectAnalysis.
 * Groups endpoints by path prefix, shows methods, handlers, and source files.
 * Includes a Mermaid sequence diagram for the most common request flows.
 */

import type { ProjectAnalysis } from "@brainst0rm/ingest";

export interface APIDoc {
  markdown: string;
  mermaidDiagram: string;
  endpointCount: number;
}

/**
 * Generate an API reference document from project analysis.
 */
export function generateAPIDoc(analysis: ProjectAnalysis): APIDoc {
  const endpoints = analysis.endpoints.endpoints;
  const lines: string[] = [];

  const projectName = analysis.projectPath.split("/").pop() ?? "Project";
  lines.push(`# ${projectName} — API Reference`);
  lines.push("");
  lines.push(
    `> Auto-generated by Brainstorm on ${new Date().toISOString().split("T")[0]}`,
  );
  lines.push("");

  if (endpoints.length === 0) {
    lines.push("No API endpoints detected.");
    return { markdown: lines.join("\n"), mermaidDiagram: "", endpointCount: 0 };
  }

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Total endpoints:** ${endpoints.length}`);
  lines.push(
    `- **Frameworks:** ${analysis.endpoints.frameworks.join(", ") || "Unknown"}`,
  );
  lines.push("");

  // Method breakdown
  const methodCounts = new Map<string, number>();
  for (const ep of endpoints) {
    methodCounts.set(ep.method, (methodCounts.get(ep.method) ?? 0) + 1);
  }
  lines.push("### Methods");
  lines.push("");
  lines.push("| Method | Count |");
  lines.push("|--------|-------|");
  for (const [method, count] of [...methodCounts.entries()].sort()) {
    lines.push(`| ${method} | ${count} |`);
  }
  lines.push("");

  // Group endpoints by path prefix
  const groups = groupEndpoints(endpoints.map((e) => ({ ...e })));

  for (const [prefix, eps] of [...groups.entries()].sort()) {
    lines.push(`## ${prefix || "/"}`);
    lines.push("");
    lines.push("| Method | Path | Handler | Source |");
    lines.push("|--------|------|---------|--------|");

    for (const ep of eps.sort((a, b) => a.path.localeCompare(b.path))) {
      const handler = ep.handler ?? "—";
      const source = `\`${ep.file}:${ep.line}\``;
      lines.push(
        `| \`${ep.method}\` | \`${ep.path}\` | ${handler} | ${source} |`,
      );
    }
    lines.push("");
  }

  // Mermaid sequence diagram for top routes
  const mermaidDiagram = generateAPIFlowDiagram(endpoints.slice(0, 10));
  if (mermaidDiagram) {
    lines.push("## Request Flow");
    lines.push("");
    lines.push("```mermaid");
    lines.push(mermaidDiagram);
    lines.push("```");
    lines.push("");
  }

  return {
    markdown: lines.join("\n"),
    mermaidDiagram: mermaidDiagram ?? "",
    endpointCount: endpoints.length,
  };
}

function groupEndpoints(
  endpoints: Array<{
    method: string;
    path: string;
    file: string;
    line: number;
    handler?: string;
  }>,
): Map<string, typeof endpoints> {
  const groups = new Map<string, typeof endpoints>();

  for (const ep of endpoints) {
    // Group by first path segment: /api/users/... → /api/users
    const parts = ep.path.split("/").filter(Boolean);
    const prefix =
      parts.length >= 2
        ? `/${parts.slice(0, 2).join("/")}`
        : `/${parts[0] ?? ""}`;

    if (!groups.has(prefix)) groups.set(prefix, []);
    groups.get(prefix)!.push(ep);
  }

  return groups;
}

function generateAPIFlowDiagram(
  endpoints: Array<{ method: string; path: string; handler?: string }>,
): string | null {
  if (endpoints.length === 0) return null;

  const lines: string[] = ["sequenceDiagram"];
  lines.push("  participant C as Client");
  lines.push("  participant S as Server");

  // Show up to 6 request flows
  for (const ep of endpoints.slice(0, 6)) {
    const handler = ep.handler ?? "handler";
    lines.push(`  C->>S: ${ep.method} ${ep.path}`);
    lines.push(`  S->>S: ${handler}()`);
    lines.push(`  S-->>C: Response`);
  }

  return lines.join("\n");
}
