/**
 * Architecture Document Generator.
 *
 * Produces a markdown architecture document from ProjectAnalysis.
 * Includes component diagram (Mermaid), data flow, deployment topology,
 * and technology stack summary.
 *
 * This is deterministic — no LLM needed. For LLM-enhanced descriptions,
 * the CLI can pass these docs as context to an agent.
 */

import type { ProjectAnalysis } from "@brainstorm/ingest";

export interface ArchitectureDoc {
  markdown: string;
  mermaidDiagram: string;
  sections: string[];
}

/**
 * Generate an architecture document from project analysis.
 */
export function generateArchitectureDoc(
  analysis: ProjectAnalysis,
): ArchitectureDoc {
  const sections: string[] = [];
  const lines: string[] = [];

  // Title
  const projectName = analysis.projectPath.split("/").pop() ?? "Project";
  lines.push(`# ${projectName} — Architecture Document`);
  lines.push("");
  lines.push(
    `> Auto-generated by Brainstorm on ${new Date().toISOString().split("T")[0]}`,
  );
  lines.push("");

  // Overview
  sections.push("Overview");
  lines.push("## Overview");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Primary Language | ${analysis.languages.primary} |`);
  lines.push(
    `| Total Files | ${analysis.summary.totalFiles.toLocaleString()} |`,
  );
  lines.push(
    `| Total Lines | ${analysis.summary.totalLines.toLocaleString()} |`,
  );
  lines.push(
    `| Frameworks | ${analysis.summary.frameworkList.join(", ") || "None detected"} |`,
  );
  lines.push(`| Modules | ${analysis.summary.moduleCount} |`);
  lines.push(`| API Routes | ${analysis.summary.apiRouteCount} |`);
  lines.push(
    `| Avg Complexity | ${analysis.summary.avgComplexity.toFixed(1)} |`,
  );
  lines.push(`| Hotspots | ${analysis.summary.hotspotCount} |`);
  lines.push("");

  // Technology Stack
  sections.push("Technology Stack");
  lines.push("## Technology Stack");
  lines.push("");
  const fw = analysis.frameworks;
  if (fw.frameworks.length > 0)
    lines.push(`- **Frameworks:** ${fw.frameworks.join(", ")}`);
  if (fw.buildTools.length > 0)
    lines.push(`- **Build Tools:** ${fw.buildTools.join(", ")}`);
  if (fw.packageManagers.length > 0)
    lines.push(`- **Package Managers:** ${fw.packageManagers.join(", ")}`);
  if (fw.databases.length > 0)
    lines.push(`- **Databases:** ${fw.databases.join(", ")}`);
  if (fw.testing.length > 0)
    lines.push(`- **Testing:** ${fw.testing.join(", ")}`);
  if (fw.ci.length > 0) lines.push(`- **CI/CD:** ${fw.ci.join(", ")}`);
  if (fw.deployment.length > 0)
    lines.push(`- **Deployment:** ${fw.deployment.join(", ")}`);
  lines.push("");

  // Language Breakdown
  sections.push("Language Breakdown");
  lines.push("## Language Breakdown");
  lines.push("");
  lines.push("| Language | Files | Lines | % |");
  lines.push("|----------|-------|-------|---|");
  for (const lang of analysis.languages.languages) {
    lines.push(
      `| ${lang.language} | ${lang.files} | ${lang.lines.toLocaleString()} | ${lang.percentage.toFixed(1)}% |`,
    );
  }
  lines.push("");

  // Component Diagram (Mermaid)
  const mermaidDiagram = generateComponentDiagram(analysis);
  sections.push("Component Diagram");
  lines.push("## Component Diagram");
  lines.push("");
  lines.push("```mermaid");
  lines.push(mermaidDiagram);
  lines.push("```");
  lines.push("");

  // Module Clusters
  if (analysis.dependencies.clusters.length > 0) {
    sections.push("Module Clusters");
    lines.push("## Module Clusters");
    lines.push("");
    for (const cluster of analysis.dependencies.clusters) {
      lines.push(`### ${cluster.directory}`);
      lines.push("");
      if (cluster.files.length <= 10) {
        for (const file of cluster.files) {
          lines.push(`- \`${file}\``);
        }
      } else {
        for (const file of cluster.files.slice(0, 10)) {
          lines.push(`- \`${file}\``);
        }
        lines.push(`- ... and ${cluster.files.length - 10} more files`);
      }
      lines.push("");
    }
  }

  // Entry Points
  if (analysis.dependencies.entryPoints.length > 0) {
    sections.push("Entry Points");
    lines.push("## Entry Points");
    lines.push("");
    for (const ep of analysis.dependencies.entryPoints) {
      lines.push(`- \`${ep}\``);
    }
    lines.push("");
  }

  // Complexity Hotspots
  if (analysis.complexity.summary.hotspots.length > 0) {
    sections.push("Complexity Hotspots");
    lines.push("## Complexity Hotspots");
    lines.push("");
    lines.push(
      "These files have the highest cyclomatic complexity and may need refactoring:",
    );
    lines.push("");
    for (const hotspot of analysis.complexity.summary.hotspots) {
      const file = analysis.complexity.files.find((f) => f.path === hotspot);
      if (file) {
        lines.push(
          `- \`${hotspot}\` — complexity: ${file.score}, ${file.lines} lines`,
        );
      } else {
        lines.push(`- \`${hotspot}\``);
      }
    }
    lines.push("");
  }

  const markdown = lines.join("\n");
  return { markdown, mermaidDiagram, sections };
}

/**
 * Generate a Mermaid component diagram from the dependency graph.
 */
function generateComponentDiagram(analysis: ProjectAnalysis): string {
  const lines: string[] = ["graph TD"];
  const clusters = analysis.dependencies.clusters;

  if (clusters.length === 0) {
    lines.push('  A["No module clusters detected"]');
    return lines.join("\n");
  }

  // Create subgraphs for each cluster
  for (let i = 0; i < Math.min(clusters.length, 8); i++) {
    const cluster = clusters[i];
    const id = sanitizeMermaidId(cluster.directory);
    lines.push(`  subgraph ${id}["${cluster.directory}"]`);
    // Show top 3 files per cluster
    const topFiles = cluster.files.slice(0, 3);
    for (let j = 0; j < topFiles.length; j++) {
      const fileId = `${id}_f${j}`;
      const fileName = topFiles[j].split("/").pop() ?? topFiles[j];
      lines.push(`    ${fileId}["${fileName}"]`);
    }
    if (cluster.files.length > 3) {
      lines.push(`    ${id}_more["+${cluster.files.length - 3} more"]`);
    }
    lines.push("  end");
  }

  // Add inter-cluster edges from the dependency graph
  const clusterMap = new Map<string, string>();
  for (const cluster of clusters) {
    for (const file of cluster.files) {
      clusterMap.set(file, cluster.directory);
    }
  }

  const edgeSet = new Set<string>();
  for (const edge of analysis.dependencies.edges.slice(0, 20)) {
    const fromCluster = clusterMap.get(edge.from);
    const toCluster = clusterMap.get(edge.to);
    if (fromCluster && toCluster && fromCluster !== toCluster) {
      const edgeKey = `${fromCluster}->${toCluster}`;
      if (!edgeSet.has(edgeKey)) {
        edgeSet.add(edgeKey);
        lines.push(
          `  ${sanitizeMermaidId(fromCluster)} --> ${sanitizeMermaidId(toCluster)}`,
        );
      }
    }
  }

  return lines.join("\n");
}

function sanitizeMermaidId(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "_");
}
