/**
 * Module Documentation Generator.
 *
 * Produces per-module (directory cluster) documentation from ProjectAnalysis.
 * Each module doc describes: purpose, key files, exports, dependencies,
 * complexity metrics, and testing status.
 */

import type { ProjectAnalysis } from "@brainstorm/ingest";
import type { ModuleCluster } from "@brainstorm/ingest";

export interface ModuleDoc {
  name: string;
  markdown: string;
}

/**
 * Generate documentation for each module cluster.
 */
export function generateModuleDocs(analysis: ProjectAnalysis): ModuleDoc[] {
  return analysis.dependencies.clusters.map((cluster) =>
    generateSingleModuleDoc(cluster, analysis),
  );
}

function generateSingleModuleDoc(
  cluster: ModuleCluster,
  analysis: ProjectAnalysis,
): ModuleDoc {
  const lines: string[] = [];

  lines.push(`# Module: ${cluster.directory}`);
  lines.push("");
  lines.push(
    `> Auto-generated by Brainstorm on ${new Date().toISOString().split("T")[0]}`,
  );
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Files:** ${cluster.files.length}`);

  const totalLines = cluster.files.reduce((sum, f) => {
    const node = analysis.dependencies.nodes.find((n) => n.path === f);
    return sum + (node?.lines ?? 0);
  }, 0);
  lines.push(`- **Lines of code:** ${totalLines.toLocaleString()}`);

  const languages = new Set(
    cluster.files
      .map(
        (f) => analysis.dependencies.nodes.find((n) => n.path === f)?.language,
      )
      .filter(Boolean),
  );
  lines.push(`- **Languages:** ${[...languages].join(", ")}`);
  lines.push("");

  // Key Files
  lines.push("## Key Files");
  lines.push("");

  // Sort files by export count (most important first)
  const filesWithExports = cluster.files
    .map((f) => {
      const node = analysis.dependencies.nodes.find((n) => n.path === f);
      return { path: f, exports: node?.exports ?? [], lines: node?.lines ?? 0 };
    })
    .sort((a, b) => b.exports.length - a.exports.length);

  for (const file of filesWithExports.slice(0, 15)) {
    const exportList =
      file.exports.length > 0
        ? ` — exports: ${file.exports.slice(0, 5).join(", ")}${file.exports.length > 5 ? ` (+${file.exports.length - 5})` : ""}`
        : "";
    lines.push(`- \`${file.path}\` (${file.lines} lines)${exportList}`);
  }
  if (filesWithExports.length > 15) {
    lines.push(`- ... and ${filesWithExports.length - 15} more files`);
  }
  lines.push("");

  // Exports
  const allExports = filesWithExports.flatMap((f) => f.exports);
  if (allExports.length > 0) {
    lines.push("## Public API");
    lines.push("");
    const uniqueExports = [...new Set(allExports)].sort();
    for (const exp of uniqueExports.slice(0, 30)) {
      lines.push(`- \`${exp}\``);
    }
    if (uniqueExports.length > 30) {
      lines.push(`- ... and ${uniqueExports.length - 30} more exports`);
    }
    lines.push("");
  }

  // Dependencies (what this module imports from outside itself)
  const externalDeps = new Set<string>();
  for (const edge of analysis.dependencies.edges) {
    if (cluster.files.includes(edge.from) && !cluster.files.includes(edge.to)) {
      // Find which cluster the target belongs to
      const targetCluster = analysis.dependencies.clusters.find((c) =>
        c.files.includes(edge.to),
      );
      if (targetCluster) {
        externalDeps.add(targetCluster.directory);
      }
    }
  }

  if (externalDeps.size > 0) {
    lines.push("## Dependencies");
    lines.push("");
    lines.push("This module depends on:");
    for (const dep of [...externalDeps].sort()) {
      lines.push(`- ${dep}`);
    }
    lines.push("");
  }

  // Dependents (what imports from this module)
  const dependents = new Set<string>();
  for (const edge of analysis.dependencies.edges) {
    if (cluster.files.includes(edge.to) && !cluster.files.includes(edge.from)) {
      const sourceCluster = analysis.dependencies.clusters.find((c) =>
        c.files.includes(edge.from),
      );
      if (sourceCluster) {
        dependents.add(sourceCluster.directory);
      }
    }
  }

  if (dependents.size > 0) {
    lines.push("## Dependents");
    lines.push("");
    lines.push("These modules depend on this one:");
    for (const dep of [...dependents].sort()) {
      lines.push(`- ${dep}`);
    }
    lines.push("");
  }

  // Complexity
  const complexFiles = cluster.files
    .map((f) => {
      const fc = analysis.complexity.files.find((cf) => cf.path === f);
      return fc ? { path: f, score: fc.score, lines: fc.lines } : null;
    })
    .filter((f): f is NonNullable<typeof f> => f !== null)
    .sort((a, b) => b.score - a.score);

  if (complexFiles.length > 0) {
    const avgScore =
      complexFiles.reduce((sum, f) => sum + f.score, 0) / complexFiles.length;
    lines.push("## Complexity");
    lines.push("");
    lines.push(`Average score: **${avgScore.toFixed(1)}/100**`);
    lines.push("");

    const hotFiles = complexFiles.filter((f) => f.score > 70);
    if (hotFiles.length > 0) {
      lines.push("Hotspots (complexity > 10):");
      for (const f of hotFiles.slice(0, 5)) {
        lines.push(
          `- \`${f.path}\` — complexity: ${f.score}, ${f.lines} lines`,
        );
      }
      lines.push("");
    }
  }

  return { name: cluster.directory, markdown: lines.join("\n") };
}
