#!/usr/bin/env tsx
/**
 * Tool Catalog Export — generates docs/tool-catalog.json
 *
 * Produces a machine-readable catalog of all brainstorm tools with:
 * - JSON Schema for each tool's inputSchema (via zod-to-json-schema)
 * - Operational metadata: permission, readonly, headlessSafe, category
 * - Protocol notes for multi-step tools
 * - Runtime discovery docs for MCP and God Mode tools
 * - Error contract specification
 *
 * Usage:
 *   npx tsx src/export-catalog.ts              # Write to docs/tool-catalog.json
 *   npx tsx src/export-catalog.ts --check      # Exit 1 if catalog is stale
 *   npx tsx src/export-catalog.ts --stdout      # Print to stdout
 */

import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { zodToJsonSchema } from "zod-to-json-schema";
import { createDefaultToolRegistry } from "./index.js";
import { resolveToolMetadata } from "./builtin/_metadata.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DOCS_PATH = resolve(__dirname, "../../../docs/tool-catalog.json");

// Category, headlessSafe, and protocol notes used to live in side-tables
// here. They moved to `builtin/_metadata.ts` so every surface (this
// generator, MCP wrappers, headless-runner gates) reads the same source.

// ── Build catalog ─────────────────────────────────────────────────

function buildCatalog(): Record<string, unknown> {
  const registry = createDefaultToolRegistry({ daemon: true });
  const allTools = registry.getAll();

  // Build category index
  const categories: Record<string, string[]> = {};
  for (const tool of allTools) {
    const resolved = resolveToolMetadata(tool.name, {
      category: tool.category,
      headlessSafe: tool.headlessSafe,
      protocol: tool.protocol,
      tags: tool.tags,
    });
    const cat = resolved?.metadata.category ?? "other";
    if (!categories[cat]) categories[cat] = [];
    categories[cat].push(tool.name);
  }

  // Build per-tool entries
  const tools: Record<string, unknown> = {};
  for (const tool of allTools) {
    let inputSchema: unknown;
    try {
      inputSchema = zodToJsonSchema(tool.inputSchema, { target: "openApi3" });
      // Remove $schema wrapper that zod-to-json-schema adds
      if (
        typeof inputSchema === "object" &&
        inputSchema !== null &&
        "$schema" in inputSchema
      ) {
        delete (inputSchema as Record<string, unknown>)["$schema"];
      }
    } catch (err) {
      // Fail-loud: a tool whose schema can't be lowered would otherwise
      // ship to docs/tool-catalog.json as an empty object, lying to MCP
      // clients about what params the tool accepts. Catalog export is a
      // build-time artifact; failing here is correct.
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(
        `zodToJsonSchema failed for tool "${tool.name}": ${msg}. ` +
          `Either fix the Zod schema or change export-catalog to handle this tool's shape explicitly.`,
      );
    }

    const resolved = resolveToolMetadata(tool.name, {
      category: tool.category,
      headlessSafe: tool.headlessSafe,
      protocol: tool.protocol,
      tags: tool.tags,
    });
    const meta = resolved?.metadata;

    tools[tool.name] = {
      description: tool.description,
      category: meta?.category ?? "other",
      permission: tool.permission,
      readonly: tool.readonly ?? false,
      headlessSafe: meta?.headlessSafe ?? false,
      ...(meta?.protocol ? { protocol: meta.protocol } : {}),
      inputSchema,
    };
  }

  return {
    $comment:
      "Machine-readable tool catalog for Brainstorm CLI. Generated by packages/tools/src/export-catalog.ts. Do not edit manually.",
    version: "0.13.0",
    generated: new Date().toISOString(),
    static: {
      toolCount: allTools.length,
      categories,
      tools,
    },
    runtime: {
      mcp: {
        description:
          "MCP tools are loaded from configured MCP servers at startup. Use tool_search to discover them.",
        discovery:
          'Call tool_search with a keyword to find and load deferred MCP tools. Example: tool_search({ query: "deploy" })',
        configLocation:
          "~/.brainstorm/mcp.json (global) or ./.brainstorm/mcp.json (project)",
      },
      godmode: {
        description:
          "God Mode tools are discovered from connected products (MSP, BR, GTM, VM, Shield) at startup via GET /api/v1/god-mode/tools.",
        discovery:
          "Products are configured in brainstorm.toml [godmode.connectors]. Each healthy product registers its tools automatically.",
        requires:
          "API key for the product set as environment variable or in vault",
        typicalCounts: {
          msp: 79,
          brainstorm_router: 10,
          gtm: 9,
          vm: 9,
          shield: 10,
        },
      },
    },
    errorContract: {
      success:
        "Tool returns a domain-specific object (e.g., { content, totalLines } for file_read)",
      failure:
        'Tool returns { error: string } (e.g., { error: "File not found: /path" })',
      detection:
        "Check for the presence of an 'error' key in the result object",
      note: "There is no unified { ok, data, error } wrapper. Each tool returns its own shape on success.",
    },
  };
}

// ── Main ──────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const checkMode = args.includes("--check");
const stdoutMode = args.includes("--stdout");

const catalog = buildCatalog();
const json = JSON.stringify(catalog, null, 2) + "\n";

if (checkMode) {
  if (!existsSync(DOCS_PATH)) {
    console.error(
      "docs/tool-catalog.json does not exist. Run: npm run export-catalog",
    );
    process.exit(1);
  }
  const existing = readFileSync(DOCS_PATH, "utf-8");
  // Compare without generated timestamp
  const normalize = (s: string) =>
    s.replace(/"generated":\s*"[^"]+"/, '"generated": ""');
  const existingHash = createHash("sha256")
    .update(normalize(existing))
    .digest("hex");
  const newHash = createHash("sha256").update(normalize(json)).digest("hex");

  if (existingHash !== newHash) {
    console.error(
      "docs/tool-catalog.json is stale. Run: npm run export-catalog",
    );
    process.exit(1);
  }
  console.log("docs/tool-catalog.json is up to date.");
  process.exit(0);
}

if (stdoutMode) {
  process.stdout.write(json);
} else {
  writeFileSync(DOCS_PATH, json);
  const toolCount = Object.keys((catalog as any).static.tools).length;
  console.log(`Wrote docs/tool-catalog.json (${toolCount} tools)`);
}
