/**
 * Dogfood test report generator.
 * Produces a markdown summary of test results.
 */

interface StepResult {
  name: string;
  model: string;
  cost: number;
  durationMs: number;
  toolCalls: number;
  success: boolean;
  error?: string;
  output: string;
}

interface Bug {
  step: string;
  error: string;
}

interface FileStat {
  path: string;
  lines: number;
  bytes: number;
}

export function generateReport(
  results: StepResult[],
  bugs: Bug[],
  fileStats: FileStat[],
): string {
  const totalCost = results.reduce((sum, r) => sum + r.cost, 0);
  const totalTime = results.reduce((sum, r) => sum + r.durationMs, 0);
  const models = new Set(results.map((r) => r.model).filter((m) => m !== 'unknown'));
  const coreSteps = results.filter((r) => !r.name.startsWith('Repair:'));
  const passed = coreSteps.filter((r) => r.success).length;

  const lines = [
    '# Brainstorm Dogfood Test Report',
    '',
    `**Date:** ${new Date().toISOString().split('T')[0]}`,
    `**Total cost:** $${totalCost.toFixed(4)}`,
    `**Total time:** ${(totalTime / 1000).toFixed(1)}s`,
    `**Steps:** ${passed}/${coreSteps.length} passed`,
    `**Models used:** ${models.size > 0 ? Array.from(models).join(', ') : 'unknown'}`,
    `**Bugs found:** ${bugs.length}`,
    '',
    '## Steps',
    '',
    '| Step | Model | Cost | Time | Tools | Status |',
    '|------|-------|------|------|-------|--------|',
  ];

  for (const r of results) {
    const status = r.success ? 'PASS' : 'FAIL';
    lines.push(
      `| ${r.name} | ${r.model} | $${r.cost.toFixed(4)} | ${(r.durationMs / 1000).toFixed(1)}s | ${r.toolCalls} | ${status} |`
    );
  }

  if (bugs.length > 0) {
    lines.push('', '## Bugs', '');
    for (const bug of bugs) {
      lines.push(`- **${bug.step}:** ${bug.error.slice(0, 200)}`);
    }
  }

  if (fileStats.length > 0) {
    lines.push('', '## Files Generated', '');
    lines.push('| File | Lines | Size |');
    lines.push('|------|-------|------|');
    for (const f of fileStats) {
      const sizeStr = f.bytes > 1024 ? `${(f.bytes / 1024).toFixed(1)}KB` : `${f.bytes}B`;
      lines.push(`| ${f.path} | ${f.lines} | ${sizeStr} |`);
    }
  }

  // Pass criteria check
  lines.push('', '## Pass Criteria', '');
  lines.push(`- [${passed === coreSteps.length ? 'x' : ' '}] All ${coreSteps.length} core steps complete`);
  lines.push(`- [${totalCost < 2.0 ? 'x' : ' '}] Total cost under $2.00 ($${totalCost.toFixed(4)})`);
  lines.push(`- [${models.size >= 2 ? 'x' : ' '}] At least 2 different models used (${models.size} found)`);

  const coreFilesExist = ['index.html', 'styles.css', 'script.js', 'video-player.js']
    .every((f) => fileStats.some((s) => s.path === f));
  lines.push(`- [${coreFilesExist ? 'x' : ' '}] All core files exist`);

  lines.push('', '---', `Generated by Brainstorm Dogfood Test`);

  return lines.join('\n');
}
